# Generated by Django 4.2.2 on 2023-06-26 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TShirt',
            new_name='Shirt',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('IN', 'Inventory'), ('SA', 'Sale')], max_length=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.shirt')),
            ],
        ),
    ]
