# Generated by Django 4.2.2 on 2023-06-26 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_tshirt_shirt_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='shirt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.shirt'),
        ),
    ]
